# ! NOTE: 
# Passwords and other sensitive data belongs into an .env file.
# see https://docs.docker.com/compose/environment-variables/set-environment-variables/ 

version: "3.9"

volumes:
  grafana-storage:
  grafana-postgres:
  timescale:

networks:
  default:
    name: monitoring-network

services:
  grafana:
    image: grafana/grafana-oss:10.1.2    # open source
    # image: grafana-custom:9.4.3       # customized image
    container_name: grafana
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-db:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=postgres
      - GF_DATABASE_SSL_MODE=disable
      # - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS= grafana-oncall-app # necessary?
      # - GF_INSTALL_PLUGINS=grafana-oncall-app
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/conf.ini:/etc/grafana/grafana.ini
    depends_on:
      - grafana-db
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  grafana-db:
    image: postgres:15.4-alpine
    container_name: grafana-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grafana
    ports:
      - 5433:5432
    volumes: 
      - grafana-postgres:/var/lib/postgresql/data
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=password    # required, otherwise timescale disable password check for all dbs 
    ports:
      - 5431:5432
    volumes: 
      - timescale:/home/postgres/pgdata/data
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
