{
 "title": "Loki Global Metrics",
 "description": "Loki metrics via 2.0",
 "tags": [
  "loki",
  "present"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Loki Global Metrics</span>\n</div>"
   },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)" }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Messages Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_internal_log_messages_total[5m])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Ruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rules Status ",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "cortex_prometheus_rule_evaluations_total",
       "legendFormat": "Evaluations"
      },
      {
       "expr": "cortex_prometheus_notifications_sent_total",
       "legendFormat": "Notifications"
      }
     ]
    },
    {
     "title": "Notifications Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_prometheus_notifications_latency_seconds[5m]))  by (quantile)",
       "legendFormat": "TP {{quantile}}"
      }
     ]
    },
    {
     "title": "Rule Evaluations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_prometheus_rule_evaluation_duration_seconds[5m]))  by (quantile)",
       "legendFormat": "TP {{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Chunk Store Chunks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_index_entries_per_chunk[5m])) by (le))",
       "legendFormat": "chunks"
      },
      { "expr": "lokichun", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Table-Manager Sync Durations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cortex_ingester_flush_queue_length[5m])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Lines / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Distributor  Received bytes / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "Batch appends sent to ingesters / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total[5m])",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Store Series / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(loki_store_series_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    },
    {}
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams)",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Streams Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(loki_ingester_streams_removed_total[5m])",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}