{
 "title": "Loki - Log monitoring",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki. Memory and CPU usage of Promtail/Loki compared against the Kubernetes memory/cpu limits and requests.",
 "tags": [
  "loki",
  "present"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Summary of alerts status",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Problems in the Loki Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of error/warning messages logged",
   "type": "timeseries",
   "description": "Total number of messages logged by Loki itself",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(level) (loki_log_messages_total{level=~\"error|warn\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Loki itself",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |= `` | logfmt | level=~\"error|warn\""
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "timeseries",
   "description": "Total number of messages logged by Promtail",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(level) (loki_log_messages_total{instance=\"promtail:9080\", level=~\"error|warn\"})",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error/warning messages logged by Promtail",
   "type": "logs",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "{container=\"promtail\"} |= `` | logfmt | level=~\"error|warn\""
    }
   ]
  },
  {
   "title": "Loki - ingester_appends_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_distributor_lines_received_total{job=\"loki\"}"
    }
   ]
  },
  {
   "title": "Promtail - sent log entries",
   "type": "timeseries",
   "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "promtail_sent_entries_total ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logging activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Streams in Loki",
   "type": "timeseries",
   "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
   ]
  },
  {
   "title": "Loki (distributor) - log entries received per second",
   "type": "timeseries",
   "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_lines_received_total[1m]) "
    }
   ]
  },
  {
   "title": "Bytes received in ingester per second",
   "type": "graph",
   "description": "The total number of uncompressed bytes received per tenant.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
    }
   ]
  }
 ]
}